apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: personality-regressor-830c95
spec:
  predictor:
    serviceAccountName: personality-regressor
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: s3://mlflow/1/830c954bfc6049fd99088d73e30874d8/artifacts/model
