apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: personality-regressor
spec:
  predictor:
    serviceAccountName: personality-regressor
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: s3://mlflow/<experiment_id>/<run_id>/artifacts/model
