apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: personality-regressor
spec:
  predictor:
    resources:
      requests:
        cpu: "0.1"
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 2Gi
    maxReplicas: 2
    serviceAccountName: personality-regressor
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: s3://mlflow/<experiment_id>/<run_id>/artifacts/model
