---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-s3-credentials
  namespace: example-ml
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgDtI6HipdGJr/Of3eVqV8bMDxcafJvfhW2mKauDKjgqHSGIxy1nc5AjH2atp/hNn4rwgPHmSWp/5BbBRRY2VdWpLWo7Qaa7wjjRk+s9Py8OBbPWlDZ/rh4DWHJQo8IB9lnLzhSpp8NKTfp/DXWvif3OwiftWeKXHwmr42/VqfCudCylDEXB2EOo99W6EMfvb97P8RIwJkOjO1K2XlMyt9p2IziYhE8VDKUpCu6kkqV+MbwtVMxT/vjCtRWJk0t0afqdKSqMiKvAep5Q+W5fPoPb4y/bTMy6lRmiLsOKOe/1pA2qOnfeGq0zCQU8kR06YsW2DTXuGVN90CcNx6qGj6vKClIB7nhm+N6mvAmzZmcT5TsAVkBF4GuAza39imjXdNDilIrV6YjWpljFQLoalEo/A7tcXFjhHrO5DLASSz6rT3cbvomOiV4BbQBaN4Fgzt3k2oxqsuFWmwVGvN7TFtXbYetKBJCSEAWE7L7qoeehwOpOQNHOCdfK4A2dmHTwG+8kaXYekoYETND1pN5T/V3Vmas66F9ff2LKAuXJui1qvUc167mXsVXbiLYzTZYhnWPAwBYDUSQTID9KZ6P6416zJQJGyGD/D5aGnXXqwI93a74M3wmPXpmQLEpoR+8DcF2xWTDWS99ZMe4+2a8wHvYsWDD95VS4gDOjRhb4M1dOdEssSHJOU/x1/Inmdi0FYxZye3p/
    AWS_SECRET_ACCESS_KEY: AgDR072hjqZcONvI0iIYv5EqGlpMXEQaMf27nzzg97jVPz+4CLwjvZw7/oXdCAz5mNA1LMmY/+jWZhxf2zmSTMNVUR8az7vBwwQi37CcyUM4CrZjHq5WhOSeAcTXxtn5+3GVLQKzEABbx9vGO1BoUZOLBaPdez3KqF/eqeA1CRa2MANTKPjSjepeuV0y+et6FKDIEN9tXq43zOsRHWuakTZxwJYW3X3frFxx6yGmDYVN+JxzOGgyvKhPAdAxIjQLS/f0AhozfZo18ghNgjBNkVzU7be72Uq2+FzINK2En4iV1biAyx42QYUqPBe/6HgCthmrJ53NdHBMsQdaXoGEeYmu29N/yqsDACVYPIHsHhNum/TMOjS9D4hnSlYqzyhvVIKAMv4RuovqyCMgImMtprPHIPQWZ8Z+mlb8Nqy63DtiJTr/NJ+DHrRms7A68YED6lB9bA1oJ2Y+l33BTj4aSswpORiC7wYwsB0oPNYVn2ZO+wbkxQxXVIQVB6vcUFb70C2vtZ8KbT5h6HRBEu8WmyQe1yhLE5zBnX0ofBU3Ukqa59wDTPUE0PRhmz5xIL+IqWRphdNT8uSKlfPhGMQfXOFhv6wqDshh2oZ3Wx0MrH1j5Pu6d2F0i0Mb/LLzY7YB++lkWxuh4kve3yHGz+4W9W8FBloTwSK6qVlMgVw97OMbAfA228jUhw5lzMW9ypyaFJnfmzlhjLHPHg==
  template:
    metadata:
      annotations:
        serving.kserve.io/s3-endpoint: mlflow-minio.mlflow
        serving.kserve.io/s3-region: us-east-2
        serving.kserve.io/s3-useanoncredential: "true"
        serving.kserve.io/s3-usehttps: "0"
      creationTimestamp: null
      name: mlflow-s3-credentials
      namespace: example-ml
    type: Opaque
