apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-s3-credentials
  namespace: example-ml
spec:
  encryptedData:
    # gitleaks ignore-line
    AWS_ACCESS_KEY_ID: AgBWKQs7+8IOW0vUbS2RTvADzGuQqHB9XT9Yo0CkEQvAv5AhAC57t60zlGsGNksQBVQJgUSRUTEVdVq+bvjQqdqpphXYWgGoBHoX2n808YWYAgwRher/gugWRoY/23jfxchbXJCyC1xSfIC/wTl+j/gTI/9n5HOWvnZ7RsiwbVJ+BzSaXLutL12HVza+u6Guv2zT/MdDbLb7kuogtpSxPFVz6kop/aAfYX08t/rP+BC38zp++q8LIXHTwZZIrJddZbTDvlGPr+MmyPpvj0VbI7nx81JAPpio+SMLIZnJGlqIT16EomsrOC/cNOU1W2KlZTgAE2Y3UI6euO6uXwQKs/bfE9/aZ7M9azTWWxGOUH/TtGMrZKF0m5ui0jLvFKzsbzNuoQRaU3kkYZGSIdnKEC2MlI3XXlQadDAffhAKFD7KawXPQag9pIZSkJ3F5M45c3rpL0qb1r4+miKYm+DwseCmI2qoHG4PAKN9VyYFe0PUT4PKEAShtPessQmkzT/1PWqHZaeRYG7dzKr2IrOIBq8STSgpHkpcyCtdoKEaXVQymXkx3KoewygtED2VoykYfhIbe3rSKssGthmwA4KXNINr9MuFXrsaGGOYwaVUEKea/UEPP/YlRbkDxiLQE6THAEbtCByh6oPXyZENWLJfn28Ezc9pjnSq0K+WOcKXwnohLQcglwD1AIiYFQC60EIRBwqluU6G
    # gitleaks ignore-line
    AWS_SECRET_ACCESS_KEY: AgCdxh4FvpiReMR877d8rqqyrtypZnvRE3FdnFbRft/EltU3Qu5MP1uIY7Uc6ANuVPPWtzSL7KECH2o3amf36JQj6T0Wg+17/MeHm5cTVViSex3uS5VzTlRyLCg7se2bgBS1/xn5mH4yTngl4q1kJnqWBPiZMG12mPIkN4X3Et7wMO3adJnIaq1OUhWsbOd+GWzlqM+8xc2gaJzfWwBup//VfgH9xJzBHtaN+0pR2jgCSRhfWdZkt0In7cr0PPAK9RV94k6m6Q2m1Y0wq5eUIkMrpFVXhoNm4+VyIifVeanxrYvOwycrZDQBfUeb31TrHFuq5IPsvvHcgg4T5OVt3kXzV18lspCknEAlJRy9+CPnoFKQzIw8d+D9/GFbpzPqsM0+c0PW2gv04gd/GY+bbLl7KC43E9RS1u4Mm5CD5H8WXMOzf4z7CPvEV53lrf8zjjAMkP4PtWL4BfE7EscJiqNpig6J03ZE9xF5euzMevGILymjf9M6Hx/JaHK0pPGMDQjNtpxUthHHYPuQsGdLtJfDFb/5XLc54m8jirZaJ1fnFfxZAnarXQqXPOtVuL9+sJDnhAI3+GrxXLGnVjrXUWdJjMpbSCNlHN9+0IL6h3jc2odgBizS/dmu8xZ6siDsARd2uoOtJBlMEMZDZmFuPhnojgfmo3G9rCfmvLmcnAUn+wfiDc8Gble6kHNNNN8Syf9CgGyNcPk9yA==
  template:
    metadata:
      annotations:
        serving.kserve.io/s3-endpoint: mlflow-minio.mlflow
        serving.kserve.io/s3-region: us-east-2
        serving.kserve.io/s3-useanoncredential: "true"
        serving.kserve.io/s3-usehttps: "0"
      name: mlflow-s3-credentials
      namespace: example-ml
    type: Opaque
