apiVersion: v1
kind: ServiceAccount
metadata:
  name: personality-regressor
  annotations:
    serving.kserve.io/s3-endpoint: mlflow-minio.mlflow # replace with your s3 endpoint e.g minio-service.kubeflow:9000
    serving.kserve.io/s3-usehttps: "0" # by default 1, if testing with minio you can set to 0
    serving.kserve.io/s3-region: us-east-2
    serving.kserve.io/s3-useanoncredential: "true" # omitting this is the same as false, if true will ignore provided credential and use anonymous credentials
secrets:
  - name: mlflow-s3-credentials
