apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airflow

resources:
  - namespace.yaml
  - application.yaml
  - credentials.sealedsecret.yaml
  - postgres.sealedsecret.yaml
  - repo.sealedsecret.yaml
