apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: example-ml
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project containing all example-ml applications
  sourceRepos:
    - "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - server: "*"
      namespace: "*"
  sourceNamespaces:
    - "*"
